const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{spawn}=require('node:child_process'),path=require('node:path'),{Pool}=require('pg');
require('dotenv').config({path:path.resolve(__dirname,'../.env')});
const db=process.env.TEST_DATABASE_URL,port=Number(process.env.TEST_LOAD_PORT||3200),base=`http://127.0.0.1:${port}`,tag=`${Date.now()}${crypto.randomBytes(2).toString('hex')}`,vehicles=15,waves=20;
const sha=v=>crypto.createHash('sha256').update(v).digest('hex');
function unsafe(url){if(!url)return'TEST_DATABASE_URL não configurada';let u;try{u=new URL(url)}catch{return'TEST_DATABASE_URL inválida'}const supabase=u.hostname.endsWith('.supabase.co')||u.hostname.endsWith('.supabase.com');if(!decodeURIComponent(u.pathname).toLowerCase().includes('test')&&!supabase)return'o nome do banco precisa conter test';if(process.env.DATABASE_URL===url)return'o banco de teste é igual ao operacional';return null}
async function ready(child){for(let i=0;i<600;i++){if(child.exitCode!==null)throw Error('API de carga encerrou');try{if((await fetch(`${base}/health`)).ok)return}catch{}await new Promise(r=>setTimeout(r,300))}throw Error('API não iniciou')}
const percentile=(values,p)=>values.slice().sort((a,b)=>a-b)[Math.min(values.length-1,Math.ceil(values.length*p)-1)];
test('1 empresa com 15 veículos simultâneos mantém velocidade e integridade',{timeout:300000},async t=>{
 const reason=unsafe(db);if(reason)return t.skip(`${reason}; carga nunca será executada no banco operacional`);
 const pool=new Pool({connectionString:db,max:3});
 try{await pool.query('SELECT 1')}catch{await pool.end().catch(()=>{});return t.skip('TEST_DATABASE_URL configurada, mas o banco de teste está indisponível')}
 const child=spawn(process.execPath,['server.js'],{cwd:path.resolve(__dirname,'..'),env:{...process.env,DATABASE_URL:db,PORT:String(port),JWT_SECRET:'load_'+tag,NODE_ENV:'test',MIGRATE_ON_START:'true'},stdio:'inherit'}),ids={company:null,vehicles:[],routes:[],restriction:null};
 try{
  await ready(child);const key='gps_emp_load_'+tag;
  ids.company=(await pool.query(`INSERT INTO empresas_integracao(nome,chave_hash,chave_prefixo)VALUES($1,$2,$3)RETURNING id`,['Carga 15 '+tag,sha('legacy_'+key),key.slice(0,16)])).rows[0].id;
  await pool.query(`INSERT INTO empresa_integracao_chaves(id_empresa,nome,chave_hash,chave_prefixo,escopos)VALUES($1,'Carga',$2,$3,ARRAY['telemetria:escrever'])`,[ids.company,sha(key),key.slice(0,16)]);
  ids.restriction=(await pool.query(`INSERT INTO restricoes_validadas(fonte,fonte_id,tipo,nome,lat,lng,limite_altura,confianca,ativa)VALUES('teste_carga',$1,'altura','Ponte carga',-19.391,-40.058,4.2,99,TRUE)RETURNING id`,['load_'+tag])).rows[0].id;
  const fleet=[];
  for(let i=0;i<vehicles;i++){const plate=`L${String(tag).slice(-3)}${String(i).padStart(3,'0')}`.slice(0,7).toUpperCase(),v=(await pool.query(`INSERT INTO veiculos(placa,modelo,comprimento,largura,peso,ativo)VALUES($1,'Carga',12,2.6,18,TRUE)RETURNING id`,[plate])).rows[0];ids.vehicles.push(v.id);await pool.query('INSERT INTO empresa_integracao_veiculos VALUES($1,$2,CURRENT_TIMESTAMP)',[ids.company,v.id]);const r=(await pool.query(`INSERT INTO rotas(nome,origem,destino,status)VALUES($1,'A','B','em_andamento')RETURNING id`,['Carga '+plate])).rows[0];ids.routes.push(r.id);await pool.query(`INSERT INTO viagens(id_rota,id_veiculo,carga,altura_total,peso_total,status,saida_real)VALUES($1,$2,'Carga alta',4.8,22,'em_andamento',CURRENT_TIMESTAMP)`,[r.id,v.id]);fleet.push({id:v.id,plate})}
  const results=[],started=Date.now();
  for(let wave=0;wave<waves;wave++)await Promise.all(fleet.map(async(v,index)=>{const before=performance.now(),lat=-19.391+(index*0.000001),lon=-40.064+(wave*0.00001);try{const response=await fetch(`${base}/integracoes/gps/localizacao`,{method:'POST',headers:{'content-type':'application/json','x-api-key':key},body:JSON.stringify({placa:v.plate,sessao_id:`carga-${tag}-${v.id}`,sequencia:wave,lat,lon,velocidade_kmh:60,direcao_graus:90,precisao_m:4,timestamp_dispositivo:new Date().toISOString()})}),data=await response.json();results.push({status:response.status,ms:performance.now()-before,v,wave,lat,lon,data})}catch(error){results.push({status:0,ms:performance.now()-before,v,wave,error:error.message})}}));
  const elapsed=Date.now()-started,ok=results.filter(r=>r.status===202),latencies=results.map(r=>r.ms),expected=vehicles*waves;
  assert.equal(results.length,expected);assert.equal(ok.length,expected);assert.equal(results.some(r=>r.status===429),false);
  for(const r of ok){assert.equal(r.data.placa,r.v.plate);assert.equal(r.data.guardiao.status,'na_fila');assert.ok(r.data.processamento_id);}
  for(let i=0;i<120;i++){const n=Number((await pool.query(`SELECT COUNT(*)::int n FROM guardiao_analises WHERE id_empresa=$1`,[ids.company])).rows[0].n);if(n>=expected)break;await new Promise(r=>setTimeout(r,250));}
  const history=(await pool.query(`SELECT id_veiculo,COUNT(*)::int n FROM historico_localizacoes WHERE id_veiculo=ANY($1::int[]) AND origem_coleta='integracao_empresa' GROUP BY id_veiculo`,[ids.vehicles])).rows,analyses=(await pool.query(`SELECT id_veiculo,COUNT(*)::int n FROM guardiao_analises WHERE id_empresa=$1 GROUP BY id_veiculo`,[ids.company])).rows,latest=(await pool.query(`SELECT id_veiculo,lat,lon FROM localizacoes WHERE id_veiculo=ANY($1::int[])`,[ids.vehicles])).rows;
  assert.equal(history.length,vehicles);assert.ok(history.every(r=>r.n===waves));assert.equal(analyses.length,vehicles);assert.ok(analyses.every(r=>r.n===waves));assert.equal(latest.length,vehicles);
  for(const v of fleet){const row=latest.find(x=>x.id_veiculo===v.id);assert.ok(row);assert.ok(Math.abs(Number(row.lon)-(-40.064+(waves-1)*0.00001))<1e-9)}
  t.diagnostic(JSON.stringify({veiculos:vehicles,posicoes:expected,sucesso:ok.length,erros:expected-ok.length,duracao_total_ms:elapsed,requisicoes_por_segundo:Number((expected/(elapsed/1000)).toFixed(2)),latencia_ms:{media:Number((latencies.reduce((a,b)=>a+b,0)/latencies.length).toFixed(2)),p50:Number(percentile(latencies,.5).toFixed(2)),p95:Number(percentile(latencies,.95).toFixed(2)),p99:Number(percentile(latencies,.99).toFixed(2)),max:Number(Math.max(...latencies).toFixed(2))},integridade:{historico:true,analises:true,ultima_posicao:true,perfil_viagem:true}}));
 }finally{if(ids.company)await pool.query('DELETE FROM empresas_integracao WHERE id=$1',[ids.company]).catch(()=>{});for(const id of ids.routes)await pool.query('DELETE FROM rotas WHERE id=$1',[id]).catch(()=>{});if(ids.restriction)await pool.query('DELETE FROM restricoes_validadas WHERE id=$1',[ids.restriction]).catch(()=>{});for(const id of ids.vehicles)await pool.query('DELETE FROM veiculos WHERE id=$1',[id]).catch(()=>{});await pool.end().catch(()=>{});child.kill('SIGTERM')}
});
