const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{spawn}=require('node:child_process'),path=require('node:path'),{Pool}=require('pg');
const db=process.env.TEST_DATABASE_URL,port=Number(process.env.TEST_API_PORT||3199),base=`http://127.0.0.1:${port}`,tag=`${Date.now()}_${crypto.randomBytes(3).toString('hex')}`;
const sha=v=>crypto.createHash('sha256').update(v).digest('hex'),plateA=`TA${tag.slice(-5)}`.toUpperCase().slice(0,7),plateB=`TB${tag.slice(-5)}`.toUpperCase().slice(0,7);
function unsafe(url){if(!url)return'TEST_DATABASE_URL não configurada';let u;try{u=new URL(url)}catch{return'TEST_DATABASE_URL inválida'}if(!decodeURIComponent(u.pathname).toLowerCase().includes('test'))return'o nome do banco precisa conter test';if(process.env.DATABASE_URL===url)return'o banco de teste é igual ao operacional';return null}
let seq=0;async function call(key,placa,extra={}){const r=await fetch(`${base}/integracoes/gps/localizacao`,{method:'POST',headers:{'content-type':'application/json','x-api-key':key},body:JSON.stringify({placa,lat:-19.391,lon:-40.064,velocidade_kmh:50,direcao_graus:90,precisao_m:5,timestamp_dispositivo:new Date().toISOString(),sessao_id:`teste-${tag}`,sequencia:seq++,...extra})});return{status:r.status,data:await r.json().catch(()=>({}))}}
async function ready(child){for(let i=0;i<150;i++){if(child.exitCode!==null)throw Error('API de teste encerrou');try{if((await fetch(`${base}/health`)).ok)return}catch{}await new Promise(r=>setTimeout(r,300))}throw Error('API não iniciou')}
test('integração empresarial real e isolada',{timeout:90000},async t=>{
 const reason=unsafe(db);if(reason)return t.skip(`${reason}; use PostgreSQL exclusivo e descartável`);
 const pool=new Pool({connectionString:db,ssl:false});
 try{await pool.query('SELECT 1')}catch{await pool.end().catch(()=>{});return t.skip('TEST_DATABASE_URL configurada, mas o banco de teste está indisponível')}
 const child=spawn(process.execPath,['server.js'],{cwd:path.resolve(__dirname,'..'),env:{...process.env,DATABASE_URL:db,PORT:String(port),JWT_SECRET:`test_${tag}`,NODE_ENV:'test',MIGRATE_ON_START:'true'},stdio:'ignore'}),ids={e:[],v:[],r:[],x:[]};
 try{
  await ready(child);
  const va=(await pool.query(`INSERT INTO veiculos(placa,modelo,comprimento,largura,peso,ativo)VALUES($1,'Teste A',12,2.6,18,TRUE)RETURNING id`,[plateA])).rows[0],vb=(await pool.query(`INSERT INTO veiculos(placa,modelo,comprimento,largura,peso,ativo)VALUES($1,'Teste B',11,2.5,16,TRUE)RETURNING id`,[plateB])).rows[0];ids.v.push(va.id,vb.id);
  async function company(name,vehicle,key){const e=(await pool.query(`INSERT INTO empresas_integracao(nome,chave_hash,chave_prefixo)VALUES($1,$2,$3)RETURNING id`,[name,sha('legacy_'+key),key.slice(0,16)])).rows[0];ids.e.push(e.id);const k=(await pool.query(`INSERT INTO empresa_integracao_chaves(id_empresa,nome,chave_hash,chave_prefixo,escopos)VALUES($1,'Teste',$2,$3,ARRAY['telemetria:escrever'])RETURNING id`,[e.id,sha(key),key.slice(0,16)])).rows[0];await pool.query(`INSERT INTO empresa_integracao_veiculos VALUES($1,$2,CURRENT_TIMESTAMP)`,[e.id,vehicle]);return{e:e.id,k:k.id}}
  const ka=`gps_emp_a_${tag}`,kb=`gps_emp_b_${tag}`,a=await company('Empresa A '+tag,va.id,ka);await company('Empresa B '+tag,vb.id,kb);
  assert.equal((await call(ka,plateA)).status,202);assert.equal((await call(kb,plateA)).status,404);
  const expired=`gps_emp_expired_${tag}`;await pool.query(`INSERT INTO empresa_integracao_chaves(id_empresa,nome,chave_hash,chave_prefixo,escopos,expira_em)VALUES($1,'Expirada',$2,$3,ARRAY['telemetria:escrever'],CURRENT_TIMESTAMP-INTERVAL '1 minute')`,[a.e,sha(expired),expired.slice(0,16)]);assert.equal((await call(expired,plateA)).status,401);
  const route=(await pool.query(`INSERT INTO rotas(nome,origem,destino,status)VALUES($1,'A','B','em_andamento')RETURNING id`,['Rota '+tag])).rows[0];ids.r.push(route.id);await pool.query(`INSERT INTO viagens(id_rota,id_veiculo,carga,altura_total,peso_total,status,saida_real)VALUES($1,$2,'Carga',4.8,22,'em_andamento',CURRENT_TIMESTAMP)`,[route.id,va.id]);
  const restriction=(await pool.query(`INSERT INTO restricoes_validadas(fonte,source_id,tipo,nome,lat,lng,limite_altura,confianca,ativa)VALUES('teste',$1,'altura','Ponte',-19.391,-40.058,4.2,.99,TRUE)RETURNING id`,['r_'+tag])).rows[0];ids.x.push(restriction.id);
  const g=await call(ka,plateA,{velocidade_kmh:60});assert.equal(g.status,202);assert.equal(g.data.guardiao.status,'na_fila');
  const kr=`gps_emp_rotated_${tag}`;await pool.query(`INSERT INTO empresa_integracao_chaves(id_empresa,nome,chave_hash,chave_prefixo,escopos)VALUES($1,'Rotacionada',$2,$3,ARRAY['telemetria:escrever'])`,[a.e,sha(kr),kr.slice(0,16)]);assert.equal((await call(ka,plateA)).status,202);assert.equal((await call(kr,plateA)).status,202);await pool.query(`UPDATE empresa_integracao_chaves SET ativo=FALSE,revogada_em=CURRENT_TIMESTAMP WHERE id=$1`,[a.k]);assert.equal((await call(ka,plateA)).status,401);assert.equal((await call(kr,plateA)).status,202);
  assert.ok((await pool.query(`SELECT COUNT(*)::int n FROM guardiao_analises WHERE id_empresa=$1`,[a.e])).rows[0].n>=4);
 }finally{for(const id of ids.e)await pool.query('DELETE FROM empresas_integracao WHERE id=$1',[id]).catch(()=>{});for(const id of ids.r)await pool.query('DELETE FROM rotas WHERE id=$1',[id]).catch(()=>{});for(const id of ids.x)await pool.query('DELETE FROM restricoes_validadas WHERE id=$1',[id]).catch(()=>{});for(const id of ids.v)await pool.query('DELETE FROM veiculos WHERE id=$1',[id]).catch(()=>{});await pool.end().catch(()=>{});child.kill('SIGTERM')}
});
