const express = require('express');

function criarRotasPortalEmpresarial({ pool, autenticar, autorizarPerfilEmpresa, auditarEmpresa }) {
    const router = express.Router();
router.get('/integracoes/portal/diagnostico',autenticar,autorizarPerfilEmpresa(['administrador','supervisor','analista','somente_leitura']),async(req,res)=>{try{const id=req.usuario.id_empresa;const veiculos=await pool.query(`SELECT v.id,v.placa,v.modelo,l.lat,l.lon,l.ultima_atualizacao,CASE WHEN l.ultima_atualizacao IS NULL THEN 'sem_dados' WHEN l.ultima_atualizacao<CURRENT_TIMESTAMP-INTERVAL '5 minutes' THEN 'offline' ELSE 'online' END AS status FROM empresa_integracao_veiculos ev JOIN veiculos v ON v.id=ev.id_veiculo LEFT JOIN localizacoes l ON l.id_veiculo=v.id WHERE ev.id_empresa=$1 ORDER BY v.placa`,[id]);const resumo=await pool.query(`SELECT COUNT(*)FILTER(WHERE sucesso)::int AS recebidas_24h,COUNT(*)FILTER(WHERE NOT sucesso)::int AS falhas_24h,ROUND(AVG(duracao_ms))::int AS latencia_media_ms,MAX(recebido_em) AS ultima_requisicao FROM integracao_requisicoes WHERE id_empresa=$1 AND recebido_em>CURRENT_TIMESTAMP-INTERVAL '24 hours'`,[id]);res.json({empresa:{id,nome:req.usuario.empresa},resumo:resumo.rows[0],veiculos:veiculos.rows});}catch(erro){res.status(500).json({erro:erro.message});}});
router.get('/integracoes/portal/historico',autenticar,autorizarPerfilEmpresa(['administrador','supervisor','analista','somente_leitura']),async(req,res)=>{try{const id=req.usuario.id_empresa,limite=Math.min(500,Math.max(1,Number(req.query.limite)||100));const r=await pool.query(`SELECT a.id,a.id_veiculo,a.status,a.alcance_km,a.riscos_encontrados,a.analisado_em,v.placa FROM guardiao_analises a JOIN veiculos v ON v.id=a.id_veiculo WHERE a.id_empresa=$1 ORDER BY a.analisado_em DESC LIMIT $2`,[id,limite]);res.json(r.rows);}catch(erro){res.status(500).json({erro:erro.message});}});
router.get('/integracoes/portal/viagens',autenticar,autorizarPerfilEmpresa(['administrador','supervisor','analista','somente_leitura']),async(req,res)=>{try{const r=await pool.query(`SELECT vg.id,vg.status,vg.carga,vg.altura_total,vg.peso_total,vg.saida_prevista,vg.saida_real,vg.chegada_prevista,vg.chegada_real,v.placa,v.modelo,rt.nome AS rota,rt.origem,rt.destino,u.nome AS motorista,tr.id AS id_trajeto,tr.metricas FROM viagens vg JOIN empresa_integracao_veiculos ev ON ev.id_veiculo=vg.id_veiculo AND ev.id_empresa=$1 JOIN veiculos v ON v.id=vg.id_veiculo JOIN rotas rt ON rt.id=vg.id_rota LEFT JOIN usuarios u ON u.id=vg.id_motorista LEFT JOIN trajetos_realizados tr ON tr.id_viagem=vg.id ORDER BY vg.criada_em DESC LIMIT 500`,[req.usuario.id_empresa]);res.json(r.rows);}catch(erro){res.status(500).json({erro:erro.message});}});
router.get('/integracoes/portal/rotas',autenticar,autorizarPerfilEmpresa(['administrador','supervisor','analista','somente_leitura']),async(req,res)=>{try{const r=await pool.query(`SELECT DISTINCT rt.id,rt.nome,rt.origem,rt.destino,rt.status,rt.criada_em FROM rotas rt LEFT JOIN viagens vg ON vg.id_rota=rt.id LEFT JOIN empresa_integracao_veiculos ev ON ev.id_veiculo=vg.id_veiculo AND ev.id_empresa=$1 WHERE rt.id_empresa=$1 OR ev.id_empresa=$1 ORDER BY rt.criada_em DESC LIMIT 500`,[req.usuario.id_empresa]);res.json(r.rows);}catch(erro){res.status(500).json({erro:erro.message});}});
router.get('/integracoes/portal/alertas',autenticar,autorizarPerfilEmpresa(['administrador','supervisor','analista','somente_leitura']),async(req,res)=>{try{const r=await pool.query(`SELECT g.id,g.id_veiculo,g.nivel,g.tipo_risco,g.distancia_km,g.tempo_estimado_min,g.placa,g.status_operacional,g.classificacao,g.ativo,g.primeiro_evento_em,g.ultimo_evento_em,g.resolvido_em,g.resolucao,v.modelo FROM guardiao_sombra_eventos g JOIN veiculos v ON v.id=g.id_veiculo WHERE g.id_empresa=$1 ORDER BY g.ultimo_evento_em DESC LIMIT 1000`,[req.usuario.id_empresa]);res.json(r.rows);}catch(erro){res.status(500).json({erro:erro.message});}});
router.get('/integracoes/portal/trajetos/:id',autenticar,autorizarPerfilEmpresa(['administrador','supervisor','analista','somente_leitura']),async(req,res)=>{try{const r=await pool.query(`SELECT tr.id,tr.id_viagem,tr.tratado_geojson,tr.metricas,tr.metodo_tratamento,tr.criado_em,tr.atualizado_em,vg.status,v.placa,u.nome AS motorista,rt.nome AS rota_nome,rt.origem,rt.destino,COALESCE(vg.rota_aprovada_geojson,re.dados_geojson,rt.dados_geojson) AS rota_planejada_geojson FROM trajetos_realizados tr JOIN viagens vg ON vg.id=tr.id_viagem JOIN empresa_integracao_veiculos ev ON ev.id_veiculo=vg.id_veiculo AND ev.id_empresa=$1 JOIN veiculos v ON v.id=tr.id_veiculo LEFT JOIN usuarios u ON u.id=tr.id_motorista JOIN rotas rt ON rt.id=vg.id_rota LEFT JOIN rotas_especificas re ON re.id=vg.id_rota_especifica WHERE tr.id_viagem=$2 LIMIT 1`,[req.usuario.id_empresa,req.params.id]);if(!r.rows.length)return res.status(404).json({erro:'Trajeto não encontrado para esta empresa.'});res.json(r.rows[0]);}catch(erro){res.status(500).json({erro:'Não foi possível carregar o trajeto.'});}});
router.get('/integracoes/portal/restricoes',autenticar,autorizarPerfilEmpresa(['administrador','supervisor','analista','somente_leitura']),async(req,res)=>{try{const r=await pool.query(`SELECT id,nome,tipo,fonte,confianca,status_confiabilidade,natureza,ativa,validado_em,valida_ate FROM restricoes_validadas WHERE id_empresa IS NULL OR id_empresa=$1 ORDER BY ativa DESC,validado_em DESC LIMIT 1000`,[req.usuario.id_empresa]);res.json(r.rows);}catch(erro){res.status(500).json({erro:erro.message});}});
router.get('/integracoes/portal/motoristas',autenticar,autorizarPerfilEmpresa(['administrador','supervisor','analista','somente_leitura']),async(req,res)=>{try{const r=await pool.query(`SELECT DISTINCT u.id,u.nome,u.id_veiculo,v.placa FROM empresa_integracao_veiculos ev JOIN veiculos v ON v.id=ev.id_veiculo LEFT JOIN usuarios u ON u.id_veiculo=v.id AND u.tipo='motorista' WHERE ev.id_empresa=$1 ORDER BY u.nome NULLS LAST`,[req.usuario.id_empresa]);res.json(r.rows);}catch(erro){res.status(500).json({erro:'Não foi possível carregar os motoristas.'});}});
router.get('/integracoes/portal/reportes',autenticar,autorizarPerfilEmpresa(['administrador','supervisor','analista','somente_leitura']),async(req,res)=>{try{const r=await pool.query(`SELECT rp.id,rp.tipo,rp.descricao,rp.status_reporte,rp.data_hora,rp.lat,rp.lon,v.placa,u.nome AS motorista FROM reportes rp JOIN empresa_integracao_veiculos ev ON ev.id_veiculo=rp.id_veiculo AND ev.id_empresa=$1 JOIN veiculos v ON v.id=rp.id_veiculo LEFT JOIN usuarios u ON u.id=rp.id_motorista ORDER BY rp.data_hora DESC LIMIT 1000`,[req.usuario.id_empresa]);res.json(r.rows);}catch(erro){res.status(500).json({erro:erro.message});}});
router.get('/integracoes/portal/perfis-composicao',autenticar,autorizarPerfilEmpresa(['administrador','supervisor','analista','somente_leitura']),async(req,res)=>{try{const r=await pool.query(`SELECT p.id,p.id_veiculo,p.nome,p.carreta,p.carga,p.altura,p.largura,p.comprimento,p.peso,p.eixos,p.ativo,p.updated_at,v.placa,v.modelo FROM perfis_composicao p JOIN empresa_integracao_veiculos ev ON ev.id_veiculo=p.id_veiculo AND ev.id_empresa=$1 JOIN veiculos v ON v.id=p.id_veiculo WHERE p.id_empresa IS NULL OR p.id_empresa=$1 ORDER BY p.ativo DESC,p.updated_at DESC`,[req.usuario.id_empresa]);res.json(r.rows);}catch(erro){res.status(500).json({erro:'Não foi possível carregar os perfis.'});}});
router.get('/integracoes/portal/notificacoes',autenticar,autorizarPerfilEmpresa(['administrador','supervisor','analista','somente_leitura']),async(req,res)=>{try{const r=await pool.query(`SELECT id,entrega_id,tipo,referencia_tipo,referencia_id,CASE WHEN destinatario='painel' THEN 'painel' WHEN destinatario='webhook' THEN 'webhook' WHEN destinatario LIKE '%@%' THEN 'email' ELSE 'canal' END AS canal,status,tentativas,proxima_tentativa_em,ultimo_erro,criado_em,enviado_em FROM notificacoes_outbox WHERE id_empresa=$1 ORDER BY criado_em DESC LIMIT 500`,[req.usuario.id_empresa]);res.json(r.rows);}catch(erro){res.status(500).json({erro:'Não foi possível carregar as notificações.'});}});
router.patch('/integracoes/portal/alertas/:id',autenticar,autorizarPerfilEmpresa(['administrador','supervisor']),async(req,res)=>{const status=String(req.body?.status||'');if(!['novo','em_analise','monitorando','resolvido','descartado'].includes(status))return res.status(400).json({erro:'Status operacional inválido.'});try{const encerrado=['resolvido','descartado'].includes(status);const r=await pool.query(`UPDATE guardiao_sombra_eventos SET status_operacional=$1,assumido_por=CASE WHEN $1 IN('em_analise','monitorando') THEN COALESCE(assumido_por,$2) ELSE assumido_por END,assumido_em=CASE WHEN $1 IN('em_analise','monitorando') THEN COALESCE(assumido_em,CURRENT_TIMESTAMP) ELSE assumido_em END,resolvido_por=CASE WHEN $3 THEN $2 ELSE resolvido_por END,resolvido_em=CASE WHEN $3 THEN CURRENT_TIMESTAMP ELSE resolvido_em END,resolucao=CASE WHEN $3 THEN $4 ELSE resolucao END,ativo=NOT $3 WHERE id=$5 AND id_empresa=$6 RETURNING *`,[status,req.usuario.id,encerrado,String(req.body?.resolucao||'').slice(0,1500),req.params.id,req.usuario.id_empresa]);if(!r.rows.length)return res.status(404).json({erro:'Alerta não encontrado para esta empresa.'});await auditarEmpresa({req,idEmpresa:req.usuario.id_empresa,acao:'ALERTA_TRATADO_PORTAL',recurso:'alerta_guardiao',recursoId:req.params.id,depois:r.rows[0]});res.json(r.rows[0]);}catch(erro){res.status(500).json({erro:erro.message});}});

    return router;
}

module.exports = { criarRotasPortalEmpresarial };
